import type { IperfConfig, OptionSpec } from './types'

export const OPTION_SPECS: OptionSpec[] = [
  {
    id: 'mode-host',
    group: 'general',
    flags: '-s / -c',
    label: '运行模式与目标',
    value: 'select',
    modes: 'both',
    protocols: 'all',
    description: '服务端监听或客户端连接目标主机。',
  },
  {
    id: 'port',
    group: 'general',
    flags: '-p, --port',
    label: '服务端端口',
    value: 'number',
    modes: 'both',
    protocols: 'all',
    description: '服务端监听端口，客户端也连接同一端口，默认 5201。',
  },
  {
    id: 'clientPort',
    group: 'client',
    flags: '--cport',
    label: '客户端端口',
    value: 'number',
    modes: ['client'],
    protocols: ['tcp', 'udp'],
    description: '绑定 TCP/UDP 数据流使用的本地客户端端口。',
  },
  {
    id: 'format',
    group: 'output',
    flags: '-f, --format',
    label: '速率单位',
    value: 'select',
    modes: 'both',
    protocols: 'all',
    description: '设置人类可读输出的速率单位。',
  },
  {
    id: 'pidfile',
    group: 'server',
    flags: '-I, --pidfile',
    label: 'PID 文件',
    value: 'string',
    modes: ['server'],
    protocols: 'all',
    description: '写出进程 ID，常用于后台服务端。',
  },
  {
    id: 'affinity',
    group: 'advanced',
    flags: '-A, --affinity',
    label: 'CPU 亲和性',
    value: 'string',
    modes: 'both',
    protocols: 'all',
    description: '设置本地或远端 CPU 亲和性，如 0 或 0,1。',
  },
  {
    id: 'bind',
    group: 'network',
    flags: '-B, --bind',
    label: '绑定地址',
    value: 'string',
    modes: 'both',
    protocols: 'all',
    description: '绑定本机地址或接口地址。',
  },
  {
    id: 'bindDev',
    group: 'network',
    flags: '--bind-dev',
    label: '绑定设备',
    value: 'string',
    modes: 'both',
    protocols: 'all',
    windowsNote: '依赖系统能力，Windows 社区构建可能不可用。',
    description: '直接绑定网络接口设备。',
  },
  {
    id: 'verbose',
    group: 'output',
    flags: '-V, --verbose',
    label: '详细输出',
    value: 'boolean',
    modes: 'both',
    protocols: 'all',
    description: '输出更详细的运行信息。',
  },
  {
    id: 'debug',
    group: 'advanced',
    flags: '-d, --debug',
    label: '调试输出',
    value: 'boolean',
    modes: 'both',
    protocols: 'all',
    description: '输出调试信息，主要用于开发诊断。',
  },
  {
    id: 'outputMode',
    group: 'output',
    flags: '-J',
    label: '输出模式',
    value: 'select',
    modes: 'both',
    protocols: 'all',
    description: '选择人类可读或完整 JSON。',
  },
  {
    id: 'logfile',
    group: 'output',
    flags: '--logfile',
    label: '日志文件',
    value: 'string',
    modes: 'both',
    protocols: 'all',
    description: '将 iperf3 输出写入指定文件。',
  },
  {
    id: 'forceflush',
    group: 'output',
    flags: '--forceflush',
    label: '实时刷新',
    value: 'boolean',
    modes: 'both',
    protocols: 'all',
    description: '每个输出间隔强制刷新，适合实时日志。',
  },
  {
    id: 'timestamps',
    group: 'output',
    flags: '--timestamps',
    label: '时间戳',
    value: 'boolean',
    modes: 'both',
    protocols: 'all',
    description: '在每行输出前追加时间戳，可附带格式。',
  },
  {
    id: 'rcvTimeout',
    group: 'advanced',
    flags: '--rcv-timeout',
    label: '接收超时',
    value: 'number',
    modes: 'both',
    protocols: 'all',
    description: '测试接收端空闲超时。',
  },
  {
    id: 'sndTimeout',
    group: 'advanced',
    flags: '--snd-timeout',
    label: '发送超时',
    value: 'number',
    modes: 'both',
    protocols: ['tcp'],
    description: '未确认 TCP 数据超时。',
  },
  {
    id: 'mptcp',
    group: 'protocol',
    flags: '-m, --mptcp',
    label: 'MPTCP',
    value: 'boolean',
    modes: ['client'],
    protocols: ['tcp'],
    windowsNote: '通常需要 Linux MPTCP 支持。',
    description: '使用 MPTCP 变体进行 TCP 测试。',
  },
  {
    id: 'daemon',
    group: 'server',
    flags: '-D, --daemon',
    label: '后台运行',
    value: 'boolean',
    modes: ['server'],
    protocols: 'all',
    windowsNote: 'Windows 上社区 iperf3 构建可能不支持守护进程语义。',
    description: '服务端后台运行。',
  },
  {
    id: 'oneOff',
    group: 'server',
    flags: '-1, --one-off',
    label: '单次连接',
    value: 'boolean',
    modes: ['server'],
    protocols: 'all',
    description: '处理一个客户端连接后退出。',
  },
  {
    id: 'idleTimeout',
    group: 'server',
    flags: '--idle-timeout',
    label: '空闲超时',
    value: 'number',
    modes: ['server'],
    protocols: 'all',
    description: '服务端空闲指定秒数后退出或重启。',
  },
  {
    id: 'serverMaxDuration',
    group: 'server',
    flags: '--server-max-duration',
    label: '最大测试时长',
    value: 'number',
    modes: ['server'],
    protocols: 'all',
    description: '限制客户端可运行的最大秒数。',
  },
  {
    id: 'serverBitrateLimit',
    group: 'server',
    flags: '--server-bitrate-limit',
    label: '服务端带宽上限',
    value: 'string',
    modes: ['server'],
    protocols: 'all',
    description: '超过服务端带宽策略时中止测试。',
  },
  {
    id: 'protocol',
    group: 'protocol',
    flags: '--udp / --sctp',
    label: '协议',
    value: 'select',
    modes: ['client'],
    protocols: 'all',
    description: '默认 TCP，可切换 UDP 或 SCTP。',
  },
  {
    id: 'connectTimeout',
    group: 'client',
    flags: '--connect-timeout',
    label: '连接超时',
    value: 'number',
    modes: ['client'],
    protocols: 'all',
    description: '建立控制连接的超时，单位毫秒。',
  },
  {
    id: 'bitrate',
    group: 'transfer',
    flags: '-b, --bitrate',
    label: '目标速率',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: 'UDP 默认 1Mbit/s，TCP/SCTP 默认不限速，可用 K/M/G/T。',
  },
  {
    id: 'pacingTimer',
    group: 'transfer',
    flags: '--pacing-timer',
    label: 'Pacing 间隔',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: 'iperf3 内部 pacing 定时器，单位微秒。',
  },
  {
    id: 'fqRate',
    group: 'transfer',
    flags: '--fq-rate',
    label: 'FQ 速率',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    windowsNote: '通常依赖 Linux fair queueing。',
    description: '套接字级 fair-queue pacing 速率。',
  },
  {
    id: 'noFqSocketPacing',
    group: 'advanced',
    flags: '--no-fq-socket-pacing',
    label: '禁用 FQ pacing',
    value: 'boolean',
    modes: ['client'],
    protocols: 'all',
    description: '已弃用，等价于 --fq-rate=0。',
  },
  {
    id: 'transferMode',
    group: 'transfer',
    flags: '-t / -n / -k',
    label: '传输终止条件',
    value: 'select',
    modes: ['client'],
    protocols: 'all',
    description: '按时间、字节数或块数结束测试，三者互斥。',
  },
  {
    id: 'length',
    group: 'transfer',
    flags: '-l, --length',
    label: '缓冲区长度',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '读写缓冲区长度，可用 K/M/G/T。',
  },
  {
    id: 'parallel',
    group: 'transfer',
    flags: '-P, --parallel',
    label: '并发流',
    value: 'number',
    modes: ['client'],
    protocols: 'all',
    description: '并行客户端流数量。',
  },
  {
    id: 'direction',
    group: 'transfer',
    flags: '-R / --bidir',
    label: '方向',
    value: 'select',
    modes: ['client'],
    protocols: 'all',
    description: '普通、反向或双向测试。',
  },
  {
    id: 'window',
    group: 'network',
    flags: '-w, --window',
    label: '窗口/缓冲区',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '套接字缓冲区或 TCP 窗口大小。',
  },
  {
    id: 'mss',
    group: 'network',
    flags: '-M, --set-mss',
    label: 'MSS',
    value: 'number',
    modes: ['client'],
    protocols: ['tcp', 'sctp'],
    description: '设置 TCP/SCTP 最大段大小。',
  },
  {
    id: 'noDelay',
    group: 'network',
    flags: '-N, --no-delay',
    label: 'No delay',
    value: 'boolean',
    modes: ['client'],
    protocols: ['tcp', 'sctp'],
    description: '禁用 Nagle 算法。',
  },
  {
    id: 'ipVersion',
    group: 'network',
    flags: '-4 / -6',
    label: 'IP 版本',
    value: 'select',
    modes: ['client'],
    protocols: 'all',
    description: '强制 IPv4 或 IPv6。',
  },
  {
    id: 'tos',
    group: 'network',
    flags: '-S, --tos',
    label: 'TOS',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '设置 IP Type of Service 位。',
  },
  {
    id: 'dscp',
    group: 'network',
    flags: '--dscp',
    label: 'DSCP',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '设置 DSCP 位，支持数字或符号。',
  },
  {
    id: 'flowlabel',
    group: 'network',
    flags: '-L, --flowlabel',
    label: 'IPv6 flow label',
    value: 'number',
    modes: ['client'],
    protocols: 'all',
    windowsNote: '当前主要由 Linux 支持。',
    description: '设置 IPv6 flow label。',
  },
  {
    id: 'xbind',
    group: 'protocol',
    flags: '-X, --xbind',
    label: 'SCTP xbind',
    value: 'string',
    modes: ['client'],
    protocols: ['sctp'],
    windowsNote: 'SCTP 通常仅 Linux/FreeBSD 构建支持。',
    description: '绑定 SCTP association 到指定链路集合。',
  },
  {
    id: 'sctpStreams',
    group: 'protocol',
    flags: '--nstreams',
    label: 'SCTP streams',
    value: 'number',
    modes: ['client'],
    protocols: ['sctp'],
    windowsNote: 'SCTP 通常仅 Linux/FreeBSD 构建支持。',
    description: '设置 SCTP stream 数量。',
  },
  {
    id: 'zerocopy',
    group: 'advanced',
    flags: '-Z, --zerocopy',
    label: 'Zero copy',
    value: 'boolean',
    modes: ['client'],
    protocols: 'all',
    description: '使用 sendfile 等零拷贝发送路径。',
  },
  {
    id: 'skipRxCopy',
    group: 'advanced',
    flags: '--skip-rx-copy',
    label: '跳过接收拷贝',
    value: 'boolean',
    modes: ['client'],
    protocols: 'all',
    description: '使用 MSG_TRUNC 忽略接收数据拷贝。',
  },
  {
    id: 'omit',
    group: 'transfer',
    flags: '-O, --omit',
    label: '预热忽略',
    value: 'number',
    modes: ['client'],
    protocols: 'all',
    description: '忽略测试开始前若干秒统计。',
  },
  {
    id: 'title',
    group: 'output',
    flags: '-T, --title',
    label: '标题前缀',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '给输出行追加标题前缀。',
  },
  {
    id: 'extraData',
    group: 'output',
    flags: '--extra-data',
    label: 'JSON 附加数据',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '在 JSON 输出中包含额外数据字段。',
  },
  {
    id: 'congestion',
    group: 'network',
    flags: '-C, --congestion',
    label: '拥塞控制',
    value: 'string',
    modes: ['client'],
    protocols: ['tcp'],
    windowsNote: '通常仅 Linux/FreeBSD 支持。',
    description: '设置 TCP 拥塞控制算法。',
  },
  {
    id: 'getServerOutput',
    group: 'output',
    flags: '--get-server-output',
    label: '获取服务端输出',
    value: 'boolean',
    modes: ['client'],
    protocols: 'all',
    description: '测试结束后获取服务端输出。',
  },
  {
    id: 'udpCounters64bit',
    group: 'protocol',
    flags: '--udp-counters-64bit',
    label: 'UDP 64 位计数',
    value: 'boolean',
    modes: ['client'],
    protocols: ['udp'],
    description: '长时或高码率 UDP 测试使用 64 位计数器。',
  },
  {
    id: 'repeatingPayload',
    group: 'protocol',
    flags: '--repeating-payload',
    label: '重复 payload',
    value: 'boolean',
    modes: ['client'],
    protocols: 'all',
    description: '使用重复字节模式，而不是随机数据。',
  },
  {
    id: 'dontFragment',
    group: 'protocol',
    flags: '--dont-fragment',
    label: '禁止 IPv4 分片',
    value: 'boolean',
    modes: ['client'],
    protocols: ['udp'],
    description: 'UDP/IPv4 测试设置 DF bit。',
  },
  {
    id: 'username',
    group: 'auth',
    flags: '--username',
    label: '认证用户名',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '向开启认证的 iperf3 服务端提交用户名。',
  },
  {
    id: 'rsaPublicKeyPath',
    group: 'auth',
    flags: '--rsa-public-key-path',
    label: 'RSA 公钥',
    value: 'string',
    modes: ['client'],
    protocols: 'all',
    description: '客户端用于加密认证凭据的 RSA 公钥。',
  },
  {
    id: 'rsaPrivateKeyPath',
    group: 'auth',
    flags: '--rsa-private-key-path',
    label: 'RSA 私钥',
    value: 'string',
    modes: ['server'],
    protocols: 'all',
    description: '服务端用于解密认证凭据的 RSA 私钥。',
  },
  {
    id: 'authorizedUsersPath',
    group: 'auth',
    flags: '--authorized-users-path',
    label: '授权用户文件',
    value: 'string',
    modes: ['server'],
    protocols: 'all',
    description: '服务端认证用户 CSV 配置文件。',
  },
  {
    id: 'timeSkewThreshold',
    group: 'auth',
    flags: '--time-skew-threshold',
    label: '时间偏移阈值',
    value: 'number',
    modes: ['server'],
    protocols: 'all',
    description: '认证过程允许的客户端/服务端时间偏移秒数。',
  },
  {
    id: 'usePkcs1Padding',
    group: 'auth',
    flags: '--use-pkcs1-padding',
    label: 'PKCS#1 padding',
    value: 'boolean',
    modes: 'both',
    protocols: 'all',
    description: '兼容旧版本 iperf3 认证 padding。',
  },
  {
    id: 'rawArgs',
    group: 'advanced',
    flags: 'raw',
    label: '专家参数',
    value: 'string',
    modes: 'both',
    protocols: 'all',
    description: '追加原始参数数组，适合跟进新版 iperf3 参数。',
  },
]

export const optionCountByGroup = OPTION_SPECS.reduce<Record<string, number>>((acc, spec) => {
  acc[spec.group] = (acc[spec.group] ?? 0) + 1
  return acc
}, {})

export function findOptionSpec(id: keyof IperfConfig | 'mode-host') {
  return OPTION_SPECS.find((spec) => spec.id === id)
}
